name: Run tests

on: [push]
jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute gradle build
        run: ./gradlew build

