name: Run tests

on: [push]
jobs:
  runTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute gradle build
        run: ./gradlew build

